version: '3.8'

services:
  app:
    build:
      context: .
    container_name: job-management
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties
